name: CI with Google Test

on:
  push:
  pull_request:

jobs:
  build-and-test-gtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure

